### ISSUE TITLE
Application crashes when you try to add new browser manually

### ISSUE THREAD

**Issue by Mart-Bogdan** [mortenn/BrowserPicker#108]
When I try to add second copy of Google chrome, application crashes for me
![image](https://github.com/mortenn/BrowserPicker/assets/775038/27833541-6376-42fe-a68a-7b9288d4afdd)

I'm getting following error message.
![image](https://github.com/mortenn/BrowserPicker/assets/775038/253d2f9b-cb0d-432d-8a1c-b063e098d08c)

Wasn't able to copy stack trace as text, because windows is closing instant after being shown. But was able to make screenshot in time. 

**I'm using this version:**  The first build with dotnet 8
 https://pipelinesghubeus26.actions.githubusercontent.com/c6ZAqO2SZWCvRXHkOtRXeBCPSs2zozzGs5vmewezWsUS1xoB2T/_apis/pipelines/1/runs/6/signedartifactscontent?artifactName=MSIX%20Release%20Package&urlExpires=2024-04-01T15%3A07%3A02.5483654Z&urlSigningMethod=HMACV2&urlSignature=ek3Id7f%2Brs9eitQ6ryoS9YunUckbpyNmtLVJJyQDFOE%3D

My inital idea was to add second chrome's profile with command line options: `--profile-directory="Profile 1"` and it crashed.

And I am unable to add it even without command line options.

**Comment by mortenn** [comment]
Please use the latest release and not that old build, I recognize the exception as one I have patched

**Comment by mortenn** [comment]
Adding browsers were very broken in many of the recent builds, only the very latest fixed that feature.
