### ISSUE TITLE
After I have added new browser and clicked Done it doesn't show on next launch

### ISSUE THREAD

**Issue by Mart-Bogdan** [mortenn/BrowserPicker#109]
Version: [v2.0.6](https://github.com/mortenn/BrowserPicker/releases/tag/v2.0.6)

After I have added new browser and clicked Done it doesn't show on next launch  when I run app from Start menu, and also when I use links with this app. 
1.
![image](https://github.com/mortenn/BrowserPicker/assets/775038/dcb05ee6-3c20-459a-8fca-8480fddb8544)
2.
![image](https://github.com/mortenn/BrowserPicker/assets/775038/09d67834-52c1-4b5c-b661-4760ed4cc7b0)
3.
![image](https://github.com/mortenn/BrowserPicker/assets/775038/d2ee0d0b-a94a-4a7f-bfa1-b1e7f27e4705)

Nevermind that on this screenshot there is `fooo` as app name. I've tried with real one. It still didn't work.

**Comment by mortenn** [comment]
it does get added to the registry, but most the properties are not saved, so it gets filtered out as invalid

**Comment by Mart-Bogdan** [comment]
I assume that registry subkey called BrowserList should be created.

![image](https://github.com/mortenn/BrowserPicker/assets/775038/e25a6da7-6053-4e5d-84fd-4950581dff0d)

But it is empty. And 3 browsers shown aren't there as well. I assume autodetected browsers aren't cached(saved) in reg?

**Comment by Mart-Bogdan** [comment]
My bad. I was looking on HKLM not HKCU

**Comment by Mart-Bogdan** [comment]
I know what's the bug is:  
![image](https://github.com/mortenn/BrowserPicker/assets/775038/b3d8ccce-d2f7-4e45-813e-c1d120e9aff2)

![image](https://github.com/mortenn/BrowserPicker/assets/775038/73cd59ce-0197-4867-9939-d868b2b75220)

It's getting name of calling method instead of name of argument.
https://github.com/mortenn/BrowserPicker/blob/2518f238f97581dfb9459f27debbacfe84e8ed45/src/BrowserPicker.Windows/AppSettings.cs#L80-L86

**Comment by Mart-Bogdan** [comment]
Wow you are so fast. thank you :-)

**Comment by mortenn** [comment]
I just happened to be at my computer and planning on looking at other bugs, you're welcome :)

**Comment by Mart-Bogdan** [comment]
```cs
        /// <summary>Throws an <see cref="ArgumentNullException"/> if <paramref name="argument"/> is null.</summary>
        /// <param name="argument">The reference type argument to validate as non-null.</param>
        /// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
        public static void ThrowIfNull([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
```

i think attribute CallerArgumentExpression is what you wanted to have

**Comment by Mart-Bogdan** [comment]
![image](https://github.com/mortenn/BrowserPicker/assets/775038/92e962cc-c3a3-4fb4-b054-581a8df2162e)

But it's still not perfect. 

I guess specifying name by hands is mos't relliable

**Comment by mortenn** [comment]
I just had to specify manually, the method being used wasn't intended to be used like I was.
