### ISSUE TITLE
'Match by' column doesn't match with registery

### ISSUE THREAD

**Issue by silver886** [mortenn/BrowserPicker#116]
After set up some rules and restart the application, the 'Match by' column doesn't match with the values in registry and it always shows 'Hosename'.

![image](https://github.com/mortenn/BrowserPicker/assets/11664880/aae63e2f-00ca-49dc-b78d-f83194c4ce4c)

Also, despite which 'Match by' option is selected, new rule will be shown as 'Hosename' in UI.

---

OS: Windows 11 Pro (23H2, 22631.3296)

**Comment by mortenn** [comment]
turned out to just be a simple copy paste programming error, thanks for the report!
