### ISSUE TITLE
Not opening new windows when no browsers are open. Will only show the browser select menu (tested on 2.1.0)

### ISSUE THREAD

**Issue by Deathbot64** [mortenn/BrowserPicker#117]
When opening a link that has a default set up (and I have it set to launch a specific browser if no defaults are found) only the menu select screen comes up. Will not open new window. 

2.0.1 works in this regard without issue.

**Comment by mortenn** [comment]
what other options have you enabled?

**Comment by Deathbot64** [comment]
The only setting I have enabled is:

![image](https://github.com/mortenn/BrowserPicker/assets/74361687/bd14aa75-b268-42a5-af0e-ac9f794ed788)

**Comment by mortenn** [comment]
The option `Ignore defaults when browser is not running` is kind of poorly labelled, I think that will do what you want, could you enable it and give it a go?

**Comment by Deathbot64** [comment]
On 2.11 it seems to be working now.
