### ISSUE TITLE
Removed rules keep re-appear

### ISSUE THREAD

**Issue by silver886** [mortenn/BrowserPicker#121]
This is an UI error makes already deleted rules appear in the `Defaults` rule list.
Restart the application can resolve this issue.

Reproduce steps:

1. Create a rule in `Defaults` tab.
2. Delete the rule by clicking the `X` on the right.
3. Create another rule.

---

OS version: 22631.3447

**Comment by mortenn** [comment]
Thanks for the report, I've patched the bug!
