### ISSUE TITLE
Publish to WinGet

### ISSUE THREAD

**Issue by felipecrs** [mortenn/BrowserPicker#131]
It would be great if I could install this application running some simple WinGet command. WinGet now allows to set dependencies as well, so that you can set .NET 8 for example.

**Comment by mortenn** [comment]
You have my permission to do that if you like, I don't personally use winget (and I reluctantly use chocolatey for a couple things)

**Comment by felipecrs** [comment]
Alright. Thanks a lot!

**Comment by mxxcon** [comment]
https://github.com/microsoft/winget-pkgs/issues/202184

**Comment by mxxcon** [comment]
This has been added in https://github.com/microsoft/winget-pkgs/pull/202228
BrowserPicker is now part of winget 😄
