### ISSUE TITLE
When will 2.1 be released?

### ISSUE THREAD

**Issue by mikeblakeuk** [mortenn/BrowserPicker#142]
Some devs are downloading the stable 2.0, some are downloading 2.1-beta.

Do you know if/when the beta will become the main release?

**Comment by mikeblakeuk** [comment]
It would also be nice to show the version number on the Ui

**Comment by mortenn** [comment]
Not really sitting on any roadmap for this one, just doing things when inspiration strikes, as it were.

**Comment by mortenn** [comment]
The only remaining milsetone for 2.1 is #87 but I could push that one out to 2.2 and do a release now I suppose

**Comment by mortenn** [comment]
If you would please add a separate issue for showing the version in the UI, I'll sort that out for a later release :)
