### ISSUE TITLE
No link to latest MSI

### ISSUE THREAD

**Issue by Lockszmith** [mortenn/BrowserPicker#17]
Nice project @mortenn, you README.md states to download the latest MSI, can you please provide a link to that (https://github.com/mortenn/BrowserPicker/releases/latest) in the README.md?

Also, if possible have the executables in a 7z or Zip file, to deploy without an MSI.

**Comment by mortenn** [comment]
Good input, I've linked to the releases page to make finding the download easier, github kind of hides that feature a bit..
