### ISSUE TITLE
Support Private Browsing for Microsoft Edge

### ISSUE THREAD

**Issue by MailYouLater** [mortenn/BrowserPicker#19]
In #6 [(Support incognito mode)](/mortenn/BrowserPicker/issues/6) you said 

> edge does not support this. https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9245247-inprivate-command-line-switch

However, there's an option to open a "New InPrivate window" in MS-Edge's Jump List, so I searched around and found that it can be launched in private mode via the command line by running

    start shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge -private

and I've tested and found that you can add a url on the end of that (don't put it in quotes though), so if you want to launch MS Edge in an InPrivate window and go to [this project on GitHub](/mortenn/BrowserPicker) BrowserPicker should execute it like

    shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge -private https://github.com/mortenn/BrowserPicker

**Comment by mortenn** [comment]
I've been trying to implement this, but unfortunately, I cannot get this working with Process.Start
It works from start/run but no matter what I try from code, I either get nothing or the url "http://-private%22https//github.com/mortenn/BrowserPicker%22"

If you can figure out how to get this working from code, I'll implement it.

**Comment by mortenn** [comment]
I spoke too soon, and was able to find the issue in the code I was working on.
This change should make it in after I finish up some cleanup :)

**Comment by mortenn** [comment]
As a bonus, this change makes file: urls work with edge!
