### ISSUE TITLE
Bug: This app does not work in Windows 10

### ISSUE THREAD

**Issue by xmha97** [mortenn/BrowserPicker#21]
Dear @mortenn 
This app does not work in Windows 10.
![BrowserPicker](https://user-images.githubusercontent.com/23485114/82260930-63a0e900-9973-11ea-8ac8-c2a2185254a8.png)
Please fix this issue

**Comment by mortenn** [comment]
I have never used it with anything but Windows 10 myself, so this is not O/S dependent, but I shall certainly take a look at this exception.

**Comment by mortenn** [comment]
@xmha97 Could you please export HKCU\Software\BrowserPicker from your computer registry and attach to the issue? Seems like something has gotten corrupted in there somehow..

**Comment by mortenn** [comment]
Just to clarify, the application does not write anything to the program files folder, it only stores settings in the current user registry hive. I need to add some error handling to the loading of data from there, but I would like to see what it is crashing on before I just add some random errorhandling code :)

**Comment by mortenn** [comment]
I would like to patch the program so this exception won't happen again.
Are you able to share the registry key from your user profile?
If not, I'll just add in some generic error handling :)

**Comment by xmha97** [comment]
Hello, I reinstalling Windows and now everything works fine.
