### ISSUE TITLE
Not all browsers can be viewed

### ISSUE THREAD

**Issue by xmha97** [mortenn/BrowserPicker#22]
Hello,
Not all browsers can be viewed.
![BrowserPicker](https://user-images.githubusercontent.com/23485114/83105985-edb62380-a0d0-11ea-9ae1-b8a057765183.gif)

Please add support scroll.
![Windows Settings](https://user-images.githubusercontent.com/23485114/83105995-f149aa80-a0d0-11ea-9ea8-b776e0ae907f.gif)

**Comment by mortenn** [comment]
Good catch! I've never really had a lot of browsers installed, so never noticed this.
