### ISSUE TITLE
Handle Teams links

### ISSUE THREAD

**Issue by stuartleeks** [mortenn/BrowserPicker#24]
Links from Microsoft Teams have 'safe link' handling, e.g. `https://staticsint.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Fazurerm%2Flatest%2Fdocs%2Fresources%2Fprivate_dns_zone_virtual_network_link&locale=en-gb.....`. which breaks default rules.

It would be great to decode the Teams link to display and use the underlying link for default rules.

**Comment by mortenn** [comment]
After reading your suggestion and PR, I thought it would be nifty to add in similar support for the most common URL shorteners.
Maybe even do a quick background fetch of any URL and look for any Location headers?
I haven't checkout how the teams API handles the redirect, but if they simply send you a Location, it would cover that case as well - but they possibly show you a jump page with a link to continue, I suppose?

**Comment by stuartleeks** [comment]
That sounds like a great idea! The teams links contain the target URL embedded in the URL launch but extending the approach to include the background fetch seems like it would fit nicely with the changes in the PR (and if I get BrowserPicker working for my scenario it is potentially something that I could send another PR for as I hit those cases 😃)
