### ISSUE TITLE
Run without installer

### ISSUE THREAD

**Issue by BenQoo** [mortenn/BrowserPicker#42]
I would like to run BrowserPicker without register it into Program list at Windows' Control Panel. Is it possible to develop or release a (portable?) version without installer?

Thank you!

**Comment by mortenn** [comment]
For it to show up in the "set default browser" in windows, it would need to add registry keys to windows.

If you want a portable, I presume you are looking to use it without elevated privileges?
I have not done any research, but I suppose there might be a per-user way to register browsers in windows, if so it would be doable.

Are you able to elaborate a bit on your use case?

**Comment by BenQoo** [comment]
Sorry for the confusion.

I would like to let BrowserPicker not be listed in the Windows `Control Panel\Programs\Programs and Features`. However, the other registry and privileges are fine if need, so the installer/uninstaller feature maybe not required in my situation.

**Comment by mortenn** [comment]
Can't really do that with an installer, as the list there is just windows reading the installed packages from the registry.
You could just install the msi and then remove the registry keys manually, or install it, copy the files, uninstall it, and use the executable from some custom location.

To get it to show up in the default browser selection dropdown, you will need to add some registry keys.
These are defined here in the source: https://github.com/mortenn/BrowserPicker/blob/master/Setup/Product.wxs#L46

The reason I have not coded the app to set these keys on startup, is to not require admin privileges to use it :)

**Comment by mortenn** [comment]
As the application settings are stored in HKCU, a portable version shouldn't require special registry configuration.
I may as well provide a stand-alone .exe with future releases.

**Comment by mortenn** [comment]
You may download Portable.7z from the v1.8.2 release and use that now :)

**Comment by mortenn** [comment]
I have built a portable version of BrowserPicker which bundles the .net runtime with the executable in [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8502821473) - but I did not make an msi for it at this time.
