### ISSUE TITLE
Always On Top Option

### ISSUE THREAD

**Issue by GravlLift** [mortenn/BrowserPicker#43]
I often find myself losing track of the browser picker window after it appears. While it can always be alt-tabbed to, it doesn't have a task bar presence, so it can get lost if you click away to another window after you open it. Additionally, in some cases it'll actually open itself behind the current window you're in (click a link in the VS Code powershell terminal seems to do this).

It'd be nice if there was an option to keep the window on top no matter what. In theory, you're going to want to select a browser immediately after opening the program, so I can't really think of a scenario in which you wouldn't want it right in front of you.

**Comment by mortenn** [comment]
Yes, I have also seen this happen now and then.
It is supposed to automatically close if it loses focus, but it seems that in some cases windows won't give it focus to begin with, which is kind of odd.

I'm not sure an "option" to make it always on top makes sense, but making it always on top certainly does.
