### ISSUE TITLE
Microsoft Edge private mode not displayed.

### ISSUE THREAD

**Issue by Ultrafeel** [mortenn/BrowserPicker#46]
Microsoft Edge private mode button isn't  displayed.
What I've tested is this works:
`
public string PrivacyArgs
{
	get
	{
		switch (Name)
		{
....
		case "Microsoft Edge":
						return " -inprivate ";
....
`

**Comment by mortenn** [comment]
Thanks for the report <3

**Comment by Ultrafeel** [comment]
@mortenn   As I see You didn't add `return " -inprivate "; .`. But it's an important part of the fix!  Actually,  maybe pre-chrome Edge uses the old key. And don't forget a trailing space

**Comment by mortenn** [comment]
@Ultrafeel thanks for notifying me, I did discover and fix that before I built the final release, so should be all good :)
Lots of changes in a short period of time here today!
