### ISSUE TITLE
Always show window on first startup after being installed

### ISSUE THREAD

**Issue by vort3** [mortenn/BrowserPicker#57]
Yes, that's the expected behavior, but probably it's not what everyone wants.

So I found the BrowserPicker a few minutes ago and wanted to at least look at it, but I had my browser open with some livestreams going etc., so I didn't want to close my browser yet. Double clicking the executable doesn't work either.

Had to look at the code to figure out how to do this, so I found a workaround:

I made a new DWORD (32 bit) value that is set to 1 in HKEY_CURRENT_USER\Software\BrowserPicker .

Can we please make some FAQ section to readme or add wiki for the project and mention this somewhere? Or even better, explain all registry keys that BrowserPicker uses.

**Comment by mortenn** [comment]
Clicking the executable is supposed to bring up the UI for configuration, I guess it must have broken at some point without getting caught. The installer is also supposed to put a shortcut in the start menu, but it seems that to has been broken?

**Comment by mortenn** [comment]
This bug should be resolved in the upcoming 1.7 and 1.8 patch releases.

**Comment by mortenn** [comment]
I just reread the issue and now realize I misread the original issue.
The bug where it was not showing up when started without a URL has been fixed, but your actual inital suggestion has not.

**Comment by mortenn** [comment]
Maybe throw in a short "welcome" introductory message with some tips?

**Comment by mortenn** [comment]
Not doing tips now, but I added a new issue for that if someone wants to contribute something at some point.

Starting from the next version, the first time the application is started by the user, it will now show the configuration window with a small welcome message being displayed.
