### ISSUE TITLE
Backport the «Copy URL» feature to 1.7

### ISSUE THREAD

**Issue by vort3** [mortenn/BrowserPicker#58]
This would be very useful, because sometimes you need just the link (for example, when some buttons in some apps try to open a link), but don't want to open your browser.

I don't plan to update to new versions anyway, because new versions require .NET 4.8 and I don't want to install it, so I'll keep using version 1.7.0. For other people that want to use old version but still want a way to copy URL to clipboard, here's the workaround:

Create a batch script (any text file with «.bat» as the extension) and paste this line: `echo | set /p dummyName="%~1" | clip`

Optionally, find any .png icon that symbolizes copying for you. You might need to change DPI so that icon is about 1 cm both vertically and horizontally.

Use the «Add browser» button to add your script as URL handler to BrowserPicker, use your icon as image, add any name you like. Worked for me on Windows 10 LTSC.

**Comment by mortenn** [comment]
I've copied the feature to the 1.7 branch and will be releasing a new build soon.
