### ISSUE TITLE
Bug with long url

### ISSUE THREAD

**Issue by jp-morvan** [mortenn/BrowserPicker#64]
Hi,
There is a limit on URL characters numbers : 547
But we've some url with more than 547 characters (ex : 1330 xD).
Here is an example : http://antispam.villejuif.fr/proxy/2/Si1DT1FCTElOQHZpbGxlanVpZi5mcg%3D%3D/eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fantispam.villejuif.fr%2Fproxy%2F2%2FSi1DT1FCTElOQHZpbGxlanVpZi5mcg%253D%253D%2Feur03.safelinks.protection.outlook.com%2F%3Furl%3Dhttp%253A%252F%252Fantispam.villejuif.fr%252Fproxy%252F2%252FSi1DT1FCTElOQHZpbGxlanVpZi5mcg%25253D%25253D%252Fteams.microsoft.com%252Fl%252Fmeetup-join%252F19%25253ameeting_YWI0YzJjZTYtNDEzNS00NzMxLWEyZWMtOGU0Yjc3MTZhMDll%252540thread.v2%252F0%253Fcontext%253D%25257b%252522Tid%252522%25253a%252522080f3eaf-1e2e-4baf-8c3b-e36006ff4ee8%252522%25252c%252522Oid%252522%25253a%25252295bca5cb-1c39-4ee0-8335-edcab9363247%252522%25257d%26data%3D04%257C01%257Csadhar%2540varonis.com%257C546c11063efe451eab7408d9b65ebe35%257C080f3eaf1e2e4baf8c3be36006ff4ee8%257C0%257C0%257C637741340306728801%257CUnknown%257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%253D%257C3000%26sdata%3DWDpEUx8RqSiTtZh7fHGagNVMg6sZwBympd%252FKaELh4aY%253D%26reserved%3D0&data=04%7C01%7Csadhar%40varonis.com%7C53782b4663484296b9de08d9ba2878ef%7C080f3eaf1e2e4baf8c3be36006ff4ee8%7C0%7C0%7C637745505286809834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FfSL0o0xu9PS8Xd3f8S0mUdsMEabgi0hl03q6l%2BsskE%3D&reserved=0

And when opened with BrowserPicker, here is the new url : http://antispam.villejuif.fr/proxy/2/Si1DT1FCTElOQHZpbGxlanVpZi5mcg%3D%3D/eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fantispam.villejuif.fr%2Fproxy%2F2%2FSi1DT1FCTElOQHZpbGxlanVpZi5mcg%253D%253D%2Feur03.safelinks.protection.outlook.com%2F%3Furl%3Dhttp%253A%252F%252Fantispam.villejuif.fr%252Fproxy%252F2%252FSi1DT1FCTElOQHZpbGxlanVpZi5mcg%25253D%25253D%252Fteams.microsoft.com%252Fl%252Fmeetup-join%252F19%25253ameeting_YWI0YzJjZTYtNDEzNS00NzMxLWEyZWMtOGU0Yjc3MTZhMDll%252540thread.v2%252F0%253Fcontext%253D%25257b%252522Tid%252522%25

**Comment by mortenn** [comment]
This seems to be limited by the .net framework..
Will try out some alternative ways of launching a process and see if that helps.

**Comment by mortenn** [comment]
The alternative way of specifying arguments I read about does not apply to .NET Framework, so I am unable to try that.
I will look further into this in the 2.0 prerelease branch, though

**Comment by mortenn** [comment]
I did just have a thought that this might be caused by the process start not disabling shell execution, so will give this another look soon.

**Comment by mortenn** [comment]
@jp-morvan could you please give 1.8.6 a test and see if that release resolves the issue for you?

**Comment by mortenn** [comment]
This appears to be working fine in the current version
