### ISSUE TITLE
"Add Browser" not working

### ISSUE THREAD

**Issue by msgerneu** [mortenn/BrowserPicker#65]
When adding browser, the dialog is hidden behind main windows. it is also not possible to move it in front, you have to move it beside so you can enter something. and of course, you need to know where to look for the window....
(newest version installed)

**Comment by mortenn** [comment]
Are you using the 2.0 prerelease or 1.8?

I suspect this is caused by the window now being AlwaysOnTop and the file picker dialogue being the native one, so this probably applies to at least 1.8 and 2.0, maybe even 1.7

**Comment by msgerneu** [comment]
Yes. 1.8.4 from 5-DEC-2021

**Comment by KyleShurtleff** [comment]
I can confirm this issue is happening to me as well on Win 11 with the 1.8.4 release.

**Comment by mortenn** [comment]
Just publised 1.8.5 which resolves this issue.
