### ISSUE TITLE
Add Browser - Chrome Profiles not working for second profile only

### ISSUE THREAD

**Issue by KyleShurtleff** [mortenn/BrowserPicker#66]
Following the directions to set up a custom browser specifically for different chrome profiles seems to not be working for an unknown reason. 

Here is the setup config:
![image](https://user-images.githubusercontent.com/5827799/148651347-63bc2fac-540a-48cd-b3c5-5d23726f2efe.png)

And here is my profile number I'm trying to use (from chrome://version) 
![image](https://user-images.githubusercontent.com/5827799/148651339-d3782e29-590b-498c-b261-3d22e588211b.png)

Saving this new browser is added to the list of browsers as expected. Clicking a link will pop BrowserPicker, but selecting the new browser ('Work' in this case) does not result in anything happening: Browser Picker window closes, but no chrome tab appears. The Profile has an active window. 

Note going thru this with my other profile (--profile-directory=Default) did not have any problems and is working as expected. 

I've re-created the profile 3 times now with no improvement. Is there anything else I can try? I'm happy to jump on a zoom call if that would help test/debug.

**Comment by mortenn** [comment]
Which version are you using?

**Comment by KyleShurtleff** [comment]
> Which version are you using?

1.8.4

**Comment by mortenn** [comment]
I wouldn't expect any difference in functionality between windows 10 and 11.
This issue sounds a bit strange, so I will need to test it out in debug and see if I can reproduce it.

**Comment by mortenn** [comment]
I have done som testing, and fortunately, this does not appear to be a bug with BrowserPicker.
You need to put "" around the profile folder name if it has a space, ie. --profile-directory="Profile 2"
This is a limitation of how command line arguments work in general.
Hope that answer is satisfactory!

**Comment by KyleShurtleff** [comment]
Thanks for the follow up! 

Would you mind updating your documentation, specifically this part?

>  Tip for Chrome Users: If you are using multiple Chrome profiles, by default if you choose Chrome it will launch in the last profile you launched Chrome with. To make it possibe for browser picker to select a profile you can create a new browser for each profile, set the program to the chrome executable, and add a command line argument to specify which profile to launch: --profile-directory=Default for the first profile, --profile-directory=Profile 1 for the second profile, and so on.

**Comment by mortenn** [comment]
Sure thing!

If you feel anything else in the document may be improved, I am happy to take pull requests as well :)
