### ISSUE TITLE
[RFE] Add a browser configuration option that allows to indicate if a url with the file:/// protocol has to be translated to a normal Windows path

### ISSUE THREAD

**Issue by claudio-salvio** [mortenn/BrowserPicker#72]
Hello,

There are **BrowserPicker** use cases where you deal with urls with **file:///** protocol.
In those cases it may sometimes be necessary for the **"browser"** (really any Windows program) to receive the **url as a Windows path**.

For this to be possible it would be necessary that **BrowserPicker** can be configured to indicate whether the **url** starting with **file:///** should be converted to a **path** when passed as a parameter to the **browser** being selected.
I think it is important that it is **configurable** at the level of **each browser** because in each case it may or may not be necessary to transform that type of url.

For example, sometimes I use commands in **Windows Terminal PowerShell tabs** that generate as output urls starting with **file:///**.
**Windows Terminal** allows you to launch the **default browser** (which in this case would be BrowserPicker) by pressing **Ctrl+Click** on the url.
The desired goal is to invoke one of the existing programs that **open** the **Windows context menu** corresponding to the file they receive as a parameter.
Some examples of such programs are: **AutohotkeyContextMenu.exe**, **Context.exe** and **WinContextMenu.exe**.

Best regards,
Claudio Salvio

P.S.: thanks for making BrowserPicker available and for the effort invested in developing it.

**Comment by mortenn** [comment]
Thanks for the suggestion, it has been implemented.
