### ISSUE TITLE
[Feature request] Option to override "Always ask" for domains with default browser assigned

### ISSUE THREAD

**Issue by rp1231** [mortenn/BrowserPicker#74]
I want browser picker to always ask except when the domain has been assigned a default browser.
An option to override "Always ask" in the configuration page would be a nice option to have.

![BrowserPicker_J2zy2Xjz1r-1](https://user-images.githubusercontent.com/47380919/167689948-477870c3-94f4-45a2-a957-375456e2522d.png)

Thanks

**Comment by mortenn** [comment]
Should be a trivial change, glad to accept a PR, but I will get to this next time I get some time to work on this app.

**Comment by rp1231** [comment]
I'm not a programmer, so wouldn't be able to do that.
I'll wait for the next version of the app.

**Comment by mortenn** [comment]
Hi, this feature is available with [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8531622953) or the next release
