### ISSUE TITLE
Anyone Having Issues with Outlook 365?

### ISSUE THREAD

**Issue by JohnMansi** [mortenn/BrowserPicker#77]
I took a look through the issues board, and didn't see anything, so I figured I'd add a question.

I've rebuilt a profile now several different times, and THIS time, keeping track of what I add or Change before I have an inevitable breakdown of MS Outlook refusing to connect to anything, and I find that it's following my setting BrowserPicker as my default browser.

I enable the "always ask" option, as I have several links for different apps that I prefer to have open in different browsers for reasons, but is seems like within a day of enabling "always ask" my Outlook will hang up on "trying to connect", and balks on even letting me add a new profile.

My gut tells me that the BrowserPicker is somehow getting in the way of Outlook's Modern Authentication, but I can't prove that.

Anyone else seen anything like this? suggest a good workaround?

**Comment by mortenn** [comment]
As I unfortunately have no way of debugging this myself, anything I could come up with would be pure conjecture.
Maybe try adding a default browser for the url that outlook opens?

**Comment by mortenn** [comment]
With the new options for default browsers in 2.0, you may want to give this another go
