### ISSUE TITLE
Still launches Edge if I don't have any browser windows open

### ISSUE THREAD

**Issue by dobesv** [mortenn/BrowserPicker#80]
When my system first starts and there aren't any browsers open, and I click a link inside an app like Slack or my mail reader, it opens Edge.

However, if I open a single Chrome browser window by any means, then click a link in Slack it pops up BrowserPicker to ask me what browser to use.

I don't have "Only when browser is running" selected in the Defaults tab.

**Comment by StarsLikeDust** [comment]
I ran into this too. Edge has a feature where it's always running in the background so it can launch faster. Once I switched that off things started working better. 

Where to find the Edge setting: https://www.windowscentral.com/how-prevent-new-microsoft-edge-running-background-windows-10

**Comment by mortenn** [comment]
That is most unfortunate, I wonder if we could check if there are any open windows with the process name of edge?
If we can read the "keep running in background" setting from the registry or somewhere, we might take that into consideration, I suppose.

**Comment by dobesv** [comment]
> I wonder if we could check if there are any open windows with the process name of edge?

I haven't quite figured out if it is even running BrowserPicker at this point.  Does this seem like something that BrowserPicker is doing?  Or some odd windows behavior?  That said I don't recall this happening with chrome set as my default browser, so maybe it is something specific to BrowserPicker, maybe some kind of bug where the logic checking what browsers are running is glitching out?

**Comment by mortenn** [comment]
This happened because edge leaves a background process running without any windows, I've amended the running browser detection code to ignore processes without a window handle, which resolves this in my testing.
