### ISSUE TITLE
Feature: Add default rule as part of selecting a browser

### ISSUE THREAD

**Issue by dobesv** [mortenn/BrowserPicker#81]
It would be pretty fancy if there was a checkbox at the bottom of the browser picker list which shows a message like 

- [ ] Remember my selection for xxx.com

where xxx.com is the domain name of the link being launched, and toggling the checkmark on and clicking a browser would add an entry to the browser default.

**Comment by mortenn** [comment]
Sounds good to me

**Comment by mortenn** [comment]
Hello, I've just rewritten the configuration part of the app and upgraded it to .NET 8, if you would be so kind as to give [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8495248070/artifacts/1372113556) a try, that'd be great!

**Comment by mortenn** [comment]
oops, wrong issue, I just read the summary. but if you do want to give that build a go anyway, great!

**Comment by mortenn** [comment]
this is now included in the [latest build](https://github.com/mortenn/BrowserPicker/actions/runs/8530993889), or in the next upcoming release, feel free to give it a go!
