### ISSUE TITLE
BrowserPicker not opening up on Windows 8.1

### ISSUE THREAD

**Issue by PanoramixTX** [mortenn/BrowserPicker#82]
Set as default to open URL (Http/https), does not popup, URL goes to open browser, W 8.1. Also how to control the time the picker allows selection. Thx

**Comment by mortenn** [comment]
There is not really any timer for browserpicker, it either shows up and waits for input or directly opens the link in your running/configured browser.
I haven't tried it out on Windows 8.1, so there might be some incompatibility, I guess?
Sorry I can't be of much more assistance with this.

**Comment by mortenn** [comment]
As support for 8.1 ended over a year ago, I have decided to close this issue, the app now requires .net 8 which I don't expect is available for windows 8.1.
