### ISSUE TITLE
How does Browser Picker add arguments ?

### ISSUE THREAD

**Issue by rp1231** [mortenn/BrowserPicker#83]
I'm using it to send a youtube url to a media player(potplayer)

It works fine if there's no argument.
But it misbehaves if I add the `/add` argument in browserpicker to add the url to the playlist.

I can open a url in  potplayer fine with this command:
```
potplayermini64 {youtube url} /add
```

**Comment by mortenn** [comment]
Hi, process launching is handled [here](https://github.com/mortenn/BrowserPicker/blob/b0802714e94bb528d9de113e362fba676458caea/src/BrowserPicker.App/ViewModel/BrowserViewModel.cs#L95)

Ie. the arguments get added in front of the url, without a space.

**Comment by mortenn** [comment]
You should just be able to add the space behind the argument in the UI, I believe

**Comment by mortenn** [comment]
There is not a debug mode in the app as such, but if you really want to debug it, you could grab visual studio community edition from Microsoft and download the source code.
Right clicking the app project you can go into properties and set the command line arguments to a url to test with and then hit F5 to launch it in debug mode.

I'll refrain from writing an entire howto debug .net apps in visual studio in this issue though :)
I am sure there are plenty of good intros on youtube if you want a crash course.

Whatever may be going on though, it seems clear that we should extend the advanced settings to enable greater control over the executed command line.
