### ISSUE TITLE
Removed browsers appear after a while

### ISSUE THREAD

**Issue by Klaster1** [mortenn/BrowserPicker#85]
How to reproduce:
1, Have more than two browsers installed
2. In the browser picker, remove several browsers so only two remain.
3. Wait for several days or weeks.

What happens:
Removed browsers appear again.

Expected:
Removed browsers stay removed forever.

OS: Window 10 19044.2130, latest Browser Picker.

**Comment by mortenn** [comment]
Removing a browser deletes it from the settings, it does not hide it.
Removal is meant for cases where the browser has been removed, or some custom browser is no longer wanted.
Browser Picker will periodically scan for new browsers, in case the user has installed some new browser.
To achieve what you want, you should click "Enabled" to disable the browser and hide it from the picker window.

Hope that helps!
