### ISSUE TITLE
Set default browser if no match on any filter

### ISSUE THREAD

**Issue by thheg** [mortenn/BrowserPicker#88]
In my use case, I have some URLs that I want to open in Edge.  The rest I want to open in Chrome and don't need a popup for this. I tried with |regex| .*, but then everything opened in Chrome. I see that in the reedme it is described that it will match on the longest, but isn't more logical to have it on the shortest? so that you can create a hierarchy of   filters. E.g. have one filter on github.com/mortenn for Edge, but have another for github.com for Opera. So that all github.com pages in except github.com/mortenn is opened in opera and github.com/mortenn in Edge

**Comment by mortenn** [comment]
Yes, that is how it is supposed to work, "the longest match" means the most specific patterns that matches will be picked.
If it matched the shortest hit first, then github.com/mortenn would not work if there was a rule for github.com as well.

**Comment by thheg** [comment]
Thanks for answering! Ok, then I misunderstood what longest matched meant. But I still I set a filter on |regex| .* for chrome, Atlassian links are open in Chrome even if I have a filter on atlassian.net for Edge. Do you have an example of a default fallback filter that works on all link except those that are more specifed

**Comment by thomasfrobieter** [comment]
I also need this, the majority of links should be opened in Firefox in my case, tried "*" and "|regex| .*" but the selection still appears.

**Comment by mortenn** [comment]
Hello, I've just rewritten the configuration part of the app and upgraded it to .NET 8, if you would be so kind as to give [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8495248070/artifacts/1372113556) a try, that'd be great!

**Comment by molohov** [comment]
I just tried this feature on the latest build, but then realized I didn't want it. However, once it is set, you cannot unset it. Could you add that feature in as well?

**Comment by mortenn** [comment]
This has been implmented in 2.0.1+
