### ISSUE TITLE
Add support for Vivaldi browser and its profiles 

### ISSUE THREAD

**Issue by molohov** [mortenn/BrowserPicker#90]
Currently I have to add the browser and its profiles manually. It would be nice if this was supported automatically.

**Comment by mortenn** [comment]
It should find any browser so long as it registers in the known locations in the windows registry.

If you are willing to check, you should find Vivaldi in one of the keys SOFTWARE\Clients\StartMenuInternet or SOFTWARE\WOW6432Node\Clients\StartMenuInternet in either HKEY_CURRENT_USER or HKEY_LOCAL_MACHINE.

If it is not listed there, it makes sense it is not showing up.
If it is listed there, there is some kind of bug in the code; in which case it would be helpful if you exported the vivaldi key from StartMenuInternet and shared the output in this issue.

**Comment by molohov** [comment]
Amongst the locations you suggested, I only found Vivaldi here:
Computer\HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE

**Comment by mortenn** [comment]
That is as expected, it would just be one of them :)

Could you export the contents of HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE and share with me?

**Comment by molohov** [comment]
Sorry for the delay. I installed Browser Picker on another new installation and it still didn't work. 
Here is the content of that registry key:

![image](https://github.com/mortenn/BrowserPicker/assets/1013095/e9d66157-5d9c-4798-acff-83670ab097fb)

**Comment by mortenn** [comment]
I actually meant the entire key, not the default value of it, sorry for the confusion :)
If you right click the Vivaldi.QTZPVHMVO7... key in the tree view, you can select export and the paste the content of that file into this issue.

**Comment by molohov** [comment]
Pasting:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE]
@="Vivaldi"

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\Capabilities]
"ApplicationDescription"="Vivaldi is a web browser that runs webpages and applications with lightning speed. It's fast, stable, and easy to use. Browse the web more safely with malware and phishing protection built into Vivaldi."
"ApplicationIcon"="C:\\Users\\blong\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe,0"
"ApplicationName"="Vivaldi"

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\Capabilities\FileAssociations]
".htm"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".html"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".mht"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".mhtml"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".pdf"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".shtml"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".svg"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".xht"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".xhtml"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
".webp"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\Capabilities\Startmenu]
"StartMenuInternet"="Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE"

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\Capabilities\URLAssociations]
"http"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"https"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"irc"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"mailto"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"mms"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"news"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"nntp"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"sms"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"smsto"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"snews"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"tel"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"urn"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"
"webcal"="VivaldiHTM.QTZPVHMVO7QTVPQDOYJYI4HPRE"

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\DefaultIcon]
@="C:\\Users\\blong\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe,0"

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\InstallInfo]
"ReinstallCommand"="\"C:\\Users\\blong\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe\" --make-default-browser"
"HideIconsCommand"="\"C:\\Users\\blong\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe\" --hide-icons"
"ShowIconsCommand"="\"C:\\Users\\blong\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe\" --show-icons"
"IconsVisible"=dword:00000001

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\shell]

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\shell\open]

[HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\Vivaldi.QTZPVHMVO7QTVPQDOYJYI4HPRE\shell\open\command]
@="\"C:\\Users\\blong\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe\""

```

**Comment by mortenn** [comment]
Hi, I imported your registry entries on my machine and launched BrowserPicker.
Vivaldi was detected and added to the list perfectly fine, though with the default icon because it is not installed on my machine.

Could you give 2.0 or 2.1.0 a go and see if it works for you now?
If it still does not show up, please check HKEY_CURRENT_USER\Software\BrowserPicker\BrowserList for any entries regarding Vivaldi

**Comment by molohov** [comment]
Confirmed that Vivaldi appears in the list now. Thanks!

Is there any way to add support for profile detection? This is something that would benefit Chrome as well. Simply put, have each profile appear as a separate browser in the list.

**Comment by mortenn** [comment]
Great!

As for profiles, please see issues #2 and #56
