### ISSUE TITLE
[Feature request] Add ability to edit existing browsers

### ISSUE THREAD

**Issue by molohov** [mortenn/BrowserPicker#91]
This is useful in a few situations:
1. You add a custom browser but aren't sure if it's working, and need to change the command 
2. You want to change the icon on one of the browsers

The only way around this is to re-add the browser.

**Comment by mortenn** [comment]
I thought it was possible to edit it, but as a workaround you can do it via regedit to avoid having to remove and readd it.

All the settings are in the HKEY_CURRENT_USER\Software\BrowserPicker registry key.

**Comment by mortenn** [comment]
This feature is included in the just released 2.0-beta3, please give it a whirl and let me know if it works ok :)
