### ISSUE TITLE
[Feature request] Add ability to backup/restore settings

### ISSUE THREAD

**Issue by molohov** [mortenn/BrowserPicker#92]
I recently reimaged my computer and had to rebuild my BrowserPicker from scratch, including the custom browsers and all the rules. It would be great if there was a way to backup these settings and restore them.

**Comment by mortenn** [comment]
That would indeed be a good feature to have.
As a workaround, it is possible to export the settings from the windows registry, and subsequently simply double-click the .reg file to import, I suggest you do this once you've got it reconfigured and save the file somewhere safe :)

You can run this command to create such an export:
`reg export HKEY_CURRENT_USER\Software\BrowserPicker browserpicker.reg`

**Comment by mortenn** [comment]
Implemented and looking like it works fine in the first 2.1.0 prerelease.
