### ISSUE TITLE
BrowserPicker does not open

### ISSUE THREAD

**Issue by Klaster1** [mortenn/BrowserPicker#94]
How to reproduce:
1. Install the [v2.0-beta3](https://github.com/mortenn/BrowserPicker/releases/tag/v2.0-beta3).
2. Have two browsers open.
3. Click a link in any application (Slack, Sublime Text).

Expected:
BrowserPicker opens, used to work in 1.x.

Observed:
BrowserPicker does not open. Presence of the link in the rule list does not affect the outcome.

**Comment by mortenn** [comment]
Hi, did you try beta 3.1?

**Comment by Klaster1** [comment]
Sorry for taking too long. Beta 3.1 does not fix the issue. Is there anything I can do to assist with debugging, does BrowserPicker have a verbose log mode?

**Comment by mortenn** [comment]
No problem, I'm being quite slow as well on this project these days ;)
There is no verbose logging mode, but the stack trace in the crash message should be enough to make a quick fix

**Comment by mortenn** [comment]
Hello, I've just rewritten the configuration part of the app and upgraded it to .NET 8, if you would be so kind as to give [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8495248070/artifacts/1372113556) a try, that'd be great!

**Comment by mortenn** [comment]
I am going to presume this works with v2.0.2, let me know if the problem persists.
