### ISSUE TITLE
Which W10 services are needed for BrowserPicker to run

### ISSUE THREAD

**Issue by Galeforce1** [mortenn/BrowserPicker#99]
I've just turned off a number of Window 10 services to make my PC run better, and now BrowserPicker has stopped working when I click a link in Mailbird (my email app).

The BrowserPicker app itself works when running from the Start menu, and I can remove & disable browsers normally.

Which W10 services are needed for BrowserPicker to run?

**Comment by mortenn** [comment]
I am not aware of any windows services it requires, it simply gets invoked as the default browser by windows and reads settings from your registry.

**Comment by Galeforce1** [comment]
Ok, thanks.

**Comment by mortenn** [comment]
I have built a portable version of BrowserPicker which bundles the .net runtime with the executable in [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8502821473) - there is a chance this would work better for you, if you want to give it a go. do not there is no msi for this version at this time.

**Comment by Galeforce1** [comment]
I've got it working now. Thanks.
